name: JS pre-setup
description: Presteps to run for all JS jobs
runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "yarn"

    - name: Turbo/Yarn cache
      uses: actions/cache@v3
      with:
        path: |
          .turbo-cache
          .yarn/cache
          '**/node_modules'
        key: turbo-yarn-${{ hashFiles('yarn.lock') }}

    - name: Install deps
      shell: bash
      run: yarn install --immutable

